### ISSUE TITLE
Make window always on top when choosing mouse position

### ISSUE THREAD

**Issue by LilleAndersen** [soni801/autoclicker#1]
**Improve set autoclicker pos.**
When i choose spesific mouse position, the autoclicker gets minimized when i choose.

**Always on foreground**
The program should always be on top when choosing a spesific autoclicker spot.

**Never on foreground when choosing**
When user click record mouse position the program should minimize so the user can se behind the program.

**Comment by soni801** [comment]
Implemented as a setting in 468f36c
